### ISSUE TITLE
Wait for the previous workflow in the same branch, if specified

### ISSUE THREAD

**Issue by strboul** [mktcode/consecutive-workflow-action#32]
Great module! I was wondering if it's possible to wait for the previous workflow from the same branch, and it seems it's possible to get this via the API.

> https://docs.github.com/en/rest/reference/actions#workflow-runs
>
>  branch | string | query | Returns workflow runs associated with a branch. Use the name of the branch of the push

I can also send a PR for this. Thanks!

**Comment by mktcode** [comment]
Thanks for the suggestion. I currently don't have time to work on this myself but if you submit a pull request I'll take the time to review and merge it. :)
