### ISSUE TITLE
Sequence is not working at all

### ISSUE THREAD

**Issue by anastasia-sapihora** [mktcode/consecutive-workflow-action#45]
I have issues with sequence, this week it just stopped working.
Any known issue?

**Comment by anastasia-sapihora** [comment]
@mktcode Please take a look

**Comment by nilsbillo** [comment]
I am experience the same issue

**Comment by nilsbillo** [comment]
It actually looks like github's rest api is broken. Can someone else validate this.
start a a workflow and try to get info 

curl https://api.github.com/repos/<USER>/<REPO>/actions/workflows/<WORKFLOW_ID>/runs\?status\=in_progress -H"Authorization: token $GITHUB_TOKEN "

**Comment by darianstlex** [comment]
it might be related to the recent github issue, rellated to the RunIDs, it was fixed, but it will take few days to reindex DB

**Comment by mktcode** [comment]
Gonna look into this during the weekend. Super sorry but can't do it right now. (tbh... didn't even know people are using this.)

**Comment by mktcode** [comment]
> it might be related to the recent github issue, related to the RunIDs, it was fixed, but it will take few days to reindex DB

Yea it seems it finds the workflows but no ID.

![image](https://user-images.githubusercontent.com/6792578/163672650-db395a85-9cf4-4e13-b541-a5484564567b.png)

I wonder why the workflows even pass at all.
https://github.com/mktcode/consecutive-workflow-action/blob/aed79535a759e4f5c43557f1f50b099758fd99df/index.js#L48
I'd expect it to get stuck here. :D Interesting.

**Comment by mktcode** [comment]
> it might be related to the recent github issue, related to the RunIDs, it was fixed, but it will take few days to reindex DB

What recent github issue? Can you share some link?

**Comment by darianstlex** [comment]
> > it might be related to the recent github issue, related to the RunIDs, it was fixed, but it will take few days to reindex DB
> 
> What happened? Can you share some link?

https://github.com/dawidd6/action-download-artifact/issues/147

**Comment by mktcode** [comment]
Oh dear... :D Let's hope it's not related to this: https://github.blog/2022-04-15-security-alert-stolen-oauth-user-tokens/

**Comment by nilsbillo** [comment]
Response from github.

The underlying issue was with Elastic search but it has been fixed, but we will not see new results for filtered lists until we have a new index.

To set expectations, this could be a couple of days. In this case, you would see the most recent runs if you remove the filter.

Elastic search backs filters in our API and UI. So unfiltered workflow runs lists will be correct, but filtered lists will be stale.

I hope this helps in the interim. I'll let you know when the re-index is complete, so you can search by filters again.

**Comment by nilsbillo** [comment]
Reindex done and seems to be working again.
