### ISSUE TITLE
Node 12 Deprecated

### ISSUE THREAD

**Issue by lewis-strong** [mktcode/consecutive-workflow-action#75]
https://github.com/mktcode/consecutive-workflow-action/blob/main/action.yml#L18

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: mktcode/consecutive-workflow-action@7e955aee180a0e1a4e7d44c58eed3ff29abfbbad

**Comment by mktcode** [comment]
Thanks! Will look into it!

**Comment by mktcode** [comment]
Merged https://github.com/mktcode/consecutive-workflow-action/pull/80 :)
